- name: configuring frontend module
  hosts: frontend
  become: yes
  tasks:
   - name: disable nginx module
     ansible.builtin.command: dnf module disable nginx -y

   - name: enable nginx module
     ansible.builtin.command: dnf module enable nginx:1.24 -y

   - name: install nginx
     ansible.builtin.package:
       name: nginx
       state: present

   - name: remove default nginx conf
     ansible.builtin.file:
       path: /etc/nginx/nginx.conf
       state: absent

   - name: copy nginx conf
     ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

   - name: remove html directory
     ansible.builtin.file:
       path: /usr/share/nginx/html
       state: absent

   - name: create html directory
     ansible.builtin.file:
       path: /usr/share/nginx/html
       state: directory

   - name: download content
     ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

   - name: extract content
     ansible.builtin.unarchive:
       src: /tmp/frontend.zip
       dest: /usr/share/nginx/html
       remote_src: yes

   - name: restart and enable nginx
     ansible.builtin.service:
       name: nginx
       state: restarted
       enabled: yes
