- name: configuring shipping server
  hosts: shipping
  become: yes
  tasks:
   - name: install maven
     ansible.builtin.dnf:
      name: maven 
      state: installed
   - name: creating user
     ansible.builtin.user:
       name: roboshop
       shell: /sbin/nologin
       home: /app
   - name: creating app
     ansible.builtin.file:
       path: /app
       state: directory
   - name: downloading the content
     ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
       path: /tmp/shipping.zip
   - name: extracting the data
     ansible.builtin.unarchive:
       src: /tmp/shipping.zip
       dest: /app
       remote_src: yes
   - name: installing dependencies
     ansible.builtin.command: mvn clean package 
     args:
       chdir: /app
   - name: renaming
     ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
     args:
       chdir: /app
   - name: copy shipping service
     ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
   
