- name: configuring user server
  hosts: user
  become: yes
  tasks:
   - name: disabling nodejs
     ansible.builtin.command: dnf module disable nodejs -y
   - name: enabling nodejs
     ansible.builtin.command: dnf module enable nodejs:20 -y
   - name: install nodejs
     ansible.builtin.dnf:
      name: nodejs
      state: installed
   - name: creating user
     ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
   - name: Creating directory
     ansible.builtin.file:
       path: /app
       state: directory
   - name: Downloading the content
     ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip
   - name: extracting the code
     ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
   - name: Installing dependencies
     community.general.npm:
      path: /app
      state: present
   - name: copy user service
     ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service
   - name: loading the data
     ansible.builtin.systemd_service:
      daemon_reload: true
   - name: start and enable service
     ansible.builtin.service:
       name: user
       state: present
       enabled: yes
